### ISSUE TITLE
NPM is out-of-date

### ISSUE THREAD

**Issue by ZheyangSong** [SimenB/csslint-stylish#37]
I noticed that the latest npm package is `v0.0.4`. Would you like to update it with your 1.0.0?

**Comment by SimenB** [comment]
0.0.4 is the latest. I'll update to 1.0.0 when it's actually tested in use (I don't use it personally any more).

Probably once gulp-csslint hits 1.0.0 😄

**Comment by ZheyangSong** [comment]
Yeah, Gulp's been more popular for some time (So sad to say goodbye to something I used to use for a long time). I'm working on a project which uses Grunt unfortunately. It's not just your package. I ran into similar maintaining problems with other Grunt packages... Probably it's good time to encourage my team switch to newer tech stack. 😄

**Comment by SimenB** [comment]
At work, we've completely switched over to just using npm scripts for task running, and webpack for bundling. Highly recommended 😉
